name: "redis-movie"

services:
  redis-docker-service:
    image: redis:latest
    container_name: redis-container-movies
    ports:
      - "6379:6379"

  k6:
    image: grafana/k6:latest
    container_name: k6
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts

  influxdb:
    image: influxdb:1.8 # ระบุ version 1.8 แทน latest
    container_name: influxdb
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false # ปิด authentication
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3090:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
