name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run tests
        run: go test -v ./...

      - name: Build
        run: go build -v ./...

      - name: Notify Discord Bot on Failure
        if: failure()
        run: |
          curl -X POST http://45.144.167.78:8099/bot/send \
            -H "Content-Type: application/json" \
            -d '{"project_name": "TicketShop-Movie", "status": "build failed on commit"}'
